### ISSUE TITLE
Structure files are missing

### ISSUE THREAD

**Issue by EclipseKnight** [nyirsh/MH3P-CQE#1]
Hey, I'm unable to build because the Structure files are missing from the root directory.

**Comment by EclipseKnight** [comment]
Also, a team and I are working on remaking mhp3rd and have been working on fixing a couple of the older editors to fit our needs. If you have any insight then maybe we could get in contact and discuss some things.

**Comment by nyirsh** [comment]
Hello!
As you can imagine, a lot of time passed since when I did tools for MH3P, memory is faulty but I'll be happy to help as much as I can. I also totally agree that some of those tools (especially mine) are old and not well coded at all.
I honestly haven't even realized that the source code I uploaded on github was missing some classes, let me see if I can find a better version on one of my older laptops/drives.

Also, will it be possible to have a direct chat over discord? I just want to learn more about this little project of you.

Have a nice day,
Davide

________________________________
Da: EclipseKnight <notifications@github.com>
Inviato: sabato 12 ottobre 2019 22:44
A: nyirsh/MH3P-CQE <MH3P-CQE@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Oggetto: Re: [nyirsh/MH3P-CQE] Structure files are missing (#1)


Also, a team and I are working on remaking mhp3rd and have been working on fixing a couple of the older editors to fit our needs. If you have any insight then maybe we could get in contact and discuss some things.

**Comment by EclipseKnight** [comment]
Yeah we can definitely chat over discord. And possibly even add you to the project's server so you can tell everyone else what you know as well. Here is my discord name EclipseKnight#2033.

**Comment by nyirsh** [comment]
Gonna push a re-written version asap!
